services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: db_name
      #POSTGRES_MULTIPLE_DATABASES: db1,db2
    networks:
      - directus_network
  cache:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - directus_network 
  directus:
    image: directus/directus:latest
    container_name: directus
    restart: always
    ports:
      - 8055:8055
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_started
    environment:
      KEY: 'random-key'
      SECRET: 'random-secret'
      ADMIN_EMAIL: adminmail@gmail.com
      ADMIN_PASSWORD: admin_pass
      DATABASE_CLIENT: pg
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DATABASE: db_name
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_ENABLED: "true"
      REDIS: redis://cache:6379
      CACHE_STORE: redis
    env_file:
      - .env
    volumes:
      - ./hooks:/directus/hooks
      - ./extensions:/directus/extensions
      - ./layouts:/directus/layouts
      - ./modules:/directus/modules
      - ./operations:/directus/operations
      - ./panels:/directus/panels
      - ./themes:/directus/themes
      - ./endpoints:/directus/endpoints
      - ./displays:/directus/displays
      - ./fields:/directus/fields
      - ./flows:/directus/flows
      - ./uploads:/directus/uploads
      - ./data/uploads:/directus/public/uploads
      - ./snapshots:/directus/snapshots/snapshot.yaml
      - ./templates:/directus/templates
      - ./config:/directus/config # Config data
    networks:
     - directus_network 
  app:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: sveltekit
    image: app-website
    user: "node"
    command: npm run dev
    restart: always
    volumes:
      - ./app2:/app
      - /app2/node_modules
    ports:
      - 3000:5137
    networks:
      - directus_network
    environment:
      ENV NODE_ENV: development
      VITE_DIRECTUS_URL: http://localhost:8055
      VITE_APP2_URL: http://localhost:3000

networks:
  directus_network:
    driver: bridge
